//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Alimentos.SWCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWCliente.WSCliente")]
    public interface WSCliente {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findClienteRequest", ReplyAction="http://service/WSCliente/findClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.findClienteResponse findCliente(ASP_Alimentos.SWCliente.findClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findClienteRequest", ReplyAction="http://service/WSCliente/findClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findClienteResponse> findClienteAsync(ASP_Alimentos.SWCliente.findClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/createClienteRequest", ReplyAction="http://service/WSCliente/createClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.createClienteResponse createCliente(ASP_Alimentos.SWCliente.createClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/createClienteRequest", ReplyAction="http://service/WSCliente/createClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.createClienteResponse> createClienteAsync(ASP_Alimentos.SWCliente.createClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/editClienteRequest", ReplyAction="http://service/WSCliente/editClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.editClienteResponse editCliente(ASP_Alimentos.SWCliente.editClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/editClienteRequest", ReplyAction="http://service/WSCliente/editClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.editClienteResponse> editClienteAsync(ASP_Alimentos.SWCliente.editClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/removeClienteRequest", ReplyAction="http://service/WSCliente/removeClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.removeClienteResponse removeCliente(ASP_Alimentos.SWCliente.removeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/removeClienteRequest", ReplyAction="http://service/WSCliente/removeClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.removeClienteResponse> removeClienteAsync(ASP_Alimentos.SWCliente.removeClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findAllClienteRequest", ReplyAction="http://service/WSCliente/findAllClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.findAllClienteResponse findAllCliente(ASP_Alimentos.SWCliente.findAllClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findAllClienteRequest", ReplyAction="http://service/WSCliente/findAllClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findAllClienteResponse> findAllClienteAsync(ASP_Alimentos.SWCliente.findAllClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findRangeClienteRequest", ReplyAction="http://service/WSCliente/findRangeClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.findRangeClienteResponse findRangeCliente(ASP_Alimentos.SWCliente.findRangeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/findRangeClienteRequest", ReplyAction="http://service/WSCliente/findRangeClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findRangeClienteResponse> findRangeClienteAsync(ASP_Alimentos.SWCliente.findRangeClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/countClienteRequest", ReplyAction="http://service/WSCliente/countClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ASP_Alimentos.SWCliente.countClienteResponse countCliente(ASP_Alimentos.SWCliente.countClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSCliente/countClienteRequest", ReplyAction="http://service/WSCliente/countClienteResponse")]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.countClienteResponse> countClienteAsync(ASP_Alimentos.SWCliente.countClienteRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoCField;
        
        private string apellidoClienteField;
        
        private string dvField;
        
        private int edadClienteField;
        
        private estadoCivil estadoCivilIdEstadoCivilField;
        
        private short idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private string nombreClienteField;
        
        private int rutField;
        
        private bool sexoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoC {
            get {
                return this.activoCField;
            }
            set {
                this.activoCField = value;
                this.RaisePropertyChanged("activoC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoCliente {
            get {
                return this.apellidoClienteField;
            }
            set {
                this.apellidoClienteField = value;
                this.RaisePropertyChanged("apellidoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edadCliente {
            get {
                return this.edadClienteField;
            }
            set {
                this.edadClienteField = value;
                this.RaisePropertyChanged("edadCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoCivil estadoCivilIdEstadoCivil {
            get {
                return this.estadoCivilIdEstadoCivilField;
            }
            set {
                this.estadoCivilIdEstadoCivilField = value;
                this.RaisePropertyChanged("estadoCivilIdEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class estadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEstadoCivilField;
        
        private short idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEstadoCivil {
            get {
                return this.descripcionEstadoCivilField;
            }
            set {
                this.descripcionEstadoCivilField = value;
                this.RaisePropertyChanged("descripcionEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dv;
        
        public findClienteRequest() {
        }
        
        public findClienteRequest(int rut, string dv) {
            this.rut = rut;
            this.dv = dv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente @return;
        
        public findClienteResponse() {
        }
        
        public findClienteResponse(ASP_Alimentos.SWCliente.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente entity;
        
        public createClienteRequest() {
        }
        
        public createClienteRequest(ASP_Alimentos.SWCliente.cliente entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createClienteResponse() {
        }
        
        public createClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente entity;
        
        public editClienteRequest() {
        }
        
        public editClienteRequest(ASP_Alimentos.SWCliente.cliente entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editClienteResponse() {
        }
        
        public editClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente entity;
        
        public removeClienteRequest() {
        }
        
        public removeClienteRequest(ASP_Alimentos.SWCliente.cliente entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeClienteResponse() {
        }
        
        public removeClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllClienteRequest {
        
        public findAllClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente[] @return;
        
        public findAllClienteResponse() {
        }
        
        public findAllClienteResponse(ASP_Alimentos.SWCliente.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeClienteRequest() {
        }
        
        public findRangeClienteRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ASP_Alimentos.SWCliente.cliente[] @return;
        
        public findRangeClienteResponse() {
        }
        
        public findRangeClienteResponse(ASP_Alimentos.SWCliente.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countCliente", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countClienteRequest {
        
        public countClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countClienteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countClienteResponse() {
        }
        
        public countClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSClienteChannel : ASP_Alimentos.SWCliente.WSCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClienteClient : System.ServiceModel.ClientBase<ASP_Alimentos.SWCliente.WSCliente>, ASP_Alimentos.SWCliente.WSCliente {
        
        public WSClienteClient() {
        }
        
        public WSClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.findClienteResponse ASP_Alimentos.SWCliente.WSCliente.findCliente(ASP_Alimentos.SWCliente.findClienteRequest request) {
            return base.Channel.findCliente(request);
        }
        
        public ASP_Alimentos.SWCliente.cliente findCliente(int rut, string dv) {
            ASP_Alimentos.SWCliente.findClienteRequest inValue = new ASP_Alimentos.SWCliente.findClienteRequest();
            inValue.rut = rut;
            inValue.dv = dv;
            ASP_Alimentos.SWCliente.findClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).findCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findClienteResponse> ASP_Alimentos.SWCliente.WSCliente.findClienteAsync(ASP_Alimentos.SWCliente.findClienteRequest request) {
            return base.Channel.findClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findClienteResponse> findClienteAsync(int rut, string dv) {
            ASP_Alimentos.SWCliente.findClienteRequest inValue = new ASP_Alimentos.SWCliente.findClienteRequest();
            inValue.rut = rut;
            inValue.dv = dv;
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).findClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.createClienteResponse ASP_Alimentos.SWCliente.WSCliente.createCliente(ASP_Alimentos.SWCliente.createClienteRequest request) {
            return base.Channel.createCliente(request);
        }
        
        public bool createCliente(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.createClienteRequest inValue = new ASP_Alimentos.SWCliente.createClienteRequest();
            inValue.entity = entity;
            ASP_Alimentos.SWCliente.createClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).createCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.createClienteResponse> ASP_Alimentos.SWCliente.WSCliente.createClienteAsync(ASP_Alimentos.SWCliente.createClienteRequest request) {
            return base.Channel.createClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.createClienteResponse> createClienteAsync(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.createClienteRequest inValue = new ASP_Alimentos.SWCliente.createClienteRequest();
            inValue.entity = entity;
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).createClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.editClienteResponse ASP_Alimentos.SWCliente.WSCliente.editCliente(ASP_Alimentos.SWCliente.editClienteRequest request) {
            return base.Channel.editCliente(request);
        }
        
        public bool editCliente(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.editClienteRequest inValue = new ASP_Alimentos.SWCliente.editClienteRequest();
            inValue.entity = entity;
            ASP_Alimentos.SWCliente.editClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).editCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.editClienteResponse> ASP_Alimentos.SWCliente.WSCliente.editClienteAsync(ASP_Alimentos.SWCliente.editClienteRequest request) {
            return base.Channel.editClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.editClienteResponse> editClienteAsync(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.editClienteRequest inValue = new ASP_Alimentos.SWCliente.editClienteRequest();
            inValue.entity = entity;
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).editClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.removeClienteResponse ASP_Alimentos.SWCliente.WSCliente.removeCliente(ASP_Alimentos.SWCliente.removeClienteRequest request) {
            return base.Channel.removeCliente(request);
        }
        
        public bool removeCliente(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.removeClienteRequest inValue = new ASP_Alimentos.SWCliente.removeClienteRequest();
            inValue.entity = entity;
            ASP_Alimentos.SWCliente.removeClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).removeCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.removeClienteResponse> ASP_Alimentos.SWCliente.WSCliente.removeClienteAsync(ASP_Alimentos.SWCliente.removeClienteRequest request) {
            return base.Channel.removeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.removeClienteResponse> removeClienteAsync(ASP_Alimentos.SWCliente.cliente entity) {
            ASP_Alimentos.SWCliente.removeClienteRequest inValue = new ASP_Alimentos.SWCliente.removeClienteRequest();
            inValue.entity = entity;
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).removeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.findAllClienteResponse ASP_Alimentos.SWCliente.WSCliente.findAllCliente(ASP_Alimentos.SWCliente.findAllClienteRequest request) {
            return base.Channel.findAllCliente(request);
        }
        
        public ASP_Alimentos.SWCliente.cliente[] findAllCliente() {
            ASP_Alimentos.SWCliente.findAllClienteRequest inValue = new ASP_Alimentos.SWCliente.findAllClienteRequest();
            ASP_Alimentos.SWCliente.findAllClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).findAllCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findAllClienteResponse> ASP_Alimentos.SWCliente.WSCliente.findAllClienteAsync(ASP_Alimentos.SWCliente.findAllClienteRequest request) {
            return base.Channel.findAllClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findAllClienteResponse> findAllClienteAsync() {
            ASP_Alimentos.SWCliente.findAllClienteRequest inValue = new ASP_Alimentos.SWCliente.findAllClienteRequest();
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).findAllClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.findRangeClienteResponse ASP_Alimentos.SWCliente.WSCliente.findRangeCliente(ASP_Alimentos.SWCliente.findRangeClienteRequest request) {
            return base.Channel.findRangeCliente(request);
        }
        
        public ASP_Alimentos.SWCliente.cliente[] findRangeCliente(System.Nullable<int>[] range) {
            ASP_Alimentos.SWCliente.findRangeClienteRequest inValue = new ASP_Alimentos.SWCliente.findRangeClienteRequest();
            inValue.range = range;
            ASP_Alimentos.SWCliente.findRangeClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).findRangeCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findRangeClienteResponse> ASP_Alimentos.SWCliente.WSCliente.findRangeClienteAsync(ASP_Alimentos.SWCliente.findRangeClienteRequest request) {
            return base.Channel.findRangeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.findRangeClienteResponse> findRangeClienteAsync(System.Nullable<int>[] range) {
            ASP_Alimentos.SWCliente.findRangeClienteRequest inValue = new ASP_Alimentos.SWCliente.findRangeClienteRequest();
            inValue.range = range;
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).findRangeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP_Alimentos.SWCliente.countClienteResponse ASP_Alimentos.SWCliente.WSCliente.countCliente(ASP_Alimentos.SWCliente.countClienteRequest request) {
            return base.Channel.countCliente(request);
        }
        
        public int countCliente() {
            ASP_Alimentos.SWCliente.countClienteRequest inValue = new ASP_Alimentos.SWCliente.countClienteRequest();
            ASP_Alimentos.SWCliente.countClienteResponse retVal = ((ASP_Alimentos.SWCliente.WSCliente)(this)).countCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.countClienteResponse> ASP_Alimentos.SWCliente.WSCliente.countClienteAsync(ASP_Alimentos.SWCliente.countClienteRequest request) {
            return base.Channel.countClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP_Alimentos.SWCliente.countClienteResponse> countClienteAsync() {
            ASP_Alimentos.SWCliente.countClienteRequest inValue = new ASP_Alimentos.SWCliente.countClienteRequest();
            return ((ASP_Alimentos.SWCliente.WSCliente)(this)).countClienteAsync(inValue);
        }
    }
}
