//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAlimentos.SWDetalle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWDetalle.WSDetalle")]
    public interface WSDetalle {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findDetalleRequest", ReplyAction="http://service/WSDetalle/findDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.findDetalleResponse findDetalle(WSFAlimentos.SWDetalle.findDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findDetalleRequest", ReplyAction="http://service/WSDetalle/findDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findDetalleResponse> findDetalleAsync(WSFAlimentos.SWDetalle.findDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/createDetalleRequest", ReplyAction="http://service/WSDetalle/createDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.createDetalleResponse createDetalle(WSFAlimentos.SWDetalle.createDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/createDetalleRequest", ReplyAction="http://service/WSDetalle/createDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalleResponse> createDetalleAsync(WSFAlimentos.SWDetalle.createDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/editDetalleRequest", ReplyAction="http://service/WSDetalle/editDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.editDetalleResponse editDetalle(WSFAlimentos.SWDetalle.editDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/editDetalleRequest", ReplyAction="http://service/WSDetalle/editDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.editDetalleResponse> editDetalleAsync(WSFAlimentos.SWDetalle.editDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/removeDetalleRequest", ReplyAction="http://service/WSDetalle/removeDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.removeDetalleResponse removeDetalle(WSFAlimentos.SWDetalle.removeDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/removeDetalleRequest", ReplyAction="http://service/WSDetalle/removeDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.removeDetalleResponse> removeDetalleAsync(WSFAlimentos.SWDetalle.removeDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findAllDetalleRequest", ReplyAction="http://service/WSDetalle/findAllDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.findAllDetalleResponse findAllDetalle(WSFAlimentos.SWDetalle.findAllDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findAllDetalleRequest", ReplyAction="http://service/WSDetalle/findAllDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findAllDetalleResponse> findAllDetalleAsync(WSFAlimentos.SWDetalle.findAllDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findRangeDetalleRequest", ReplyAction="http://service/WSDetalle/findRangeDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.findRangeDetalleResponse findRangeDetalle(WSFAlimentos.SWDetalle.findRangeDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/findRangeDetalleRequest", ReplyAction="http://service/WSDetalle/findRangeDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findRangeDetalleResponse> findRangeDetalleAsync(WSFAlimentos.SWDetalle.findRangeDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/countDetalleRequest", ReplyAction="http://service/WSDetalle/countDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.countDetalleResponse countDetalle(WSFAlimentos.SWDetalle.countDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/countDetalleRequest", ReplyAction="http://service/WSDetalle/countDetalleResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.countDetalleResponse> countDetalleAsync(WSFAlimentos.SWDetalle.countDetalleRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/createDetalle2Request", ReplyAction="http://service/WSDetalle/createDetalle2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWDetalle.createDetalle2Response createDetalle2(WSFAlimentos.SWDetalle.createDetalle2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSDetalle/createDetalle2Request", ReplyAction="http://service/WSDetalle/createDetalle2Response")]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalle2Response> createDetalle2Async(WSFAlimentos.SWDetalle.createDetalle2Request request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class detalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private boleta boletaIdBoletaField;
        
        private float idDetalleField;
        
        private bool idDetalleFieldSpecified;
        
        private producto productoIdProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public boleta boletaIdBoleta {
            get {
                return this.boletaIdBoletaField;
            }
            set {
                this.boletaIdBoletaField = value;
                this.RaisePropertyChanged("boletaIdBoleta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float idDetalle {
            get {
                return this.idDetalleField;
            }
            set {
                this.idDetalleField = value;
                this.RaisePropertyChanged("idDetalle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDetalleSpecified {
            get {
                return this.idDetalleFieldSpecified;
            }
            set {
                this.idDetalleFieldSpecified = value;
                this.RaisePropertyChanged("idDetalleSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public producto productoIdProducto {
            get {
                return this.productoIdProductoField;
            }
            set {
                this.productoIdProductoField = value;
                this.RaisePropertyChanged("productoIdProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class boleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idBoletaField;
        
        private bool idBoletaFieldSpecified;
        
        private ventas ventasIdventasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idBoleta {
            get {
                return this.idBoletaField;
            }
            set {
                this.idBoletaField = value;
                this.RaisePropertyChanged("idBoleta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idBoletaSpecified {
            get {
                return this.idBoletaFieldSpecified;
            }
            set {
                this.idBoletaFieldSpecified = value;
                this.RaisePropertyChanged("idBoletaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ventas ventasIdventas {
            get {
                return this.ventasIdventasField;
            }
            set {
                this.ventasIdventasField = value;
                this.RaisePropertyChanged("ventasIdventas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class ventas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoVField;
        
        private cliente clienteIdClienteField;
        
        private System.DateTime fechaEntregaField;
        
        private bool fechaEntregaFieldSpecified;
        
        private System.DateTime fechaVentaField;
        
        private bool fechaVentaFieldSpecified;
        
        private int idventasField;
        
        private bool idventasFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoV {
            get {
                return this.activoVField;
            }
            set {
                this.activoVField = value;
                this.RaisePropertyChanged("activoV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente clienteIdCliente {
            get {
                return this.clienteIdClienteField;
            }
            set {
                this.clienteIdClienteField = value;
                this.RaisePropertyChanged("clienteIdCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEntregaSpecified {
            get {
                return this.fechaEntregaFieldSpecified;
            }
            set {
                this.fechaEntregaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEntregaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVenta {
            get {
                return this.fechaVentaField;
            }
            set {
                this.fechaVentaField = value;
                this.RaisePropertyChanged("fechaVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVentaSpecified {
            get {
                return this.fechaVentaFieldSpecified;
            }
            set {
                this.fechaVentaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVentaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idventas {
            get {
                return this.idventasField;
            }
            set {
                this.idventasField = value;
                this.RaisePropertyChanged("idventas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idventasSpecified {
            get {
                return this.idventasFieldSpecified;
            }
            set {
                this.idventasFieldSpecified = value;
                this.RaisePropertyChanged("idventasSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoCField;
        
        private string apellidoClienteField;
        
        private string dvField;
        
        private int edadClienteField;
        
        private estadoCivil estadoCivilIdEstadoCivilField;
        
        private short idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private string nombreClienteField;
        
        private int rutField;
        
        private bool sexoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoC {
            get {
                return this.activoCField;
            }
            set {
                this.activoCField = value;
                this.RaisePropertyChanged("activoC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoCliente {
            get {
                return this.apellidoClienteField;
            }
            set {
                this.apellidoClienteField = value;
                this.RaisePropertyChanged("apellidoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edadCliente {
            get {
                return this.edadClienteField;
            }
            set {
                this.edadClienteField = value;
                this.RaisePropertyChanged("edadCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoCivil estadoCivilIdEstadoCivil {
            get {
                return this.estadoCivilIdEstadoCivilField;
            }
            set {
                this.estadoCivilIdEstadoCivilField = value;
                this.RaisePropertyChanged("estadoCivilIdEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class estadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEstadoCivilField;
        
        private short idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEstadoCivil {
            get {
                return this.descripcionEstadoCivilField;
            }
            set {
                this.descripcionEstadoCivilField = value;
                this.RaisePropertyChanged("descripcionEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class tipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionTpField;
        
        private short idTpField;
        
        private bool idTpFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionTp {
            get {
                return this.descripcionTpField;
            }
            set {
                this.descripcionTpField = value;
                this.RaisePropertyChanged("descripcionTp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
                this.RaisePropertyChanged("idTp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTpSpecified {
            get {
                return this.idTpFieldSpecified;
            }
            set {
                this.idTpFieldSpecified = value;
                this.RaisePropertyChanged("idTpSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class subtipoProductoPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short subtipoPField;
        
        private short tipoProductoIdTpField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short subtipoP {
            get {
                return this.subtipoPField;
            }
            set {
                this.subtipoPField = value;
                this.RaisePropertyChanged("subtipoP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short tipoProductoIdTp {
            get {
                return this.tipoProductoIdTpField;
            }
            set {
                this.tipoProductoIdTpField = value;
                this.RaisePropertyChanged("tipoProductoIdTp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class subtipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionStpField;
        
        private subtipoProductoPK subtipoProductoPKField;
        
        private tipoProducto tipoProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionStp {
            get {
                return this.descripcionStpField;
            }
            set {
                this.descripcionStpField = value;
                this.RaisePropertyChanged("descripcionStp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public subtipoProductoPK subtipoProductoPK {
            get {
                return this.subtipoProductoPKField;
            }
            set {
                this.subtipoProductoPKField = value;
                this.RaisePropertyChanged("subtipoProductoPK");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime anioFField;
        
        private bool anioFFieldSpecified;
        
        private System.DateTime anioVField;
        
        private bool anioVFieldSpecified;
        
        private string descripcionProductoField;
        
        private short idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string nombreProductoField;
        
        private int precioProductoField;
        
        private int stockField;
        
        private subtipoProducto subtipoProductoField;
        
        private double tarificacionField;
        
        private bool tarificacionFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime anioF {
            get {
                return this.anioFField;
            }
            set {
                this.anioFField = value;
                this.RaisePropertyChanged("anioF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioFSpecified {
            get {
                return this.anioFFieldSpecified;
            }
            set {
                this.anioFFieldSpecified = value;
                this.RaisePropertyChanged("anioFSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime anioV {
            get {
                return this.anioVField;
            }
            set {
                this.anioVField = value;
                this.RaisePropertyChanged("anioV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioVSpecified {
            get {
                return this.anioVFieldSpecified;
            }
            set {
                this.anioVFieldSpecified = value;
                this.RaisePropertyChanged("anioVSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
                this.RaisePropertyChanged("descripcionProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                this.precioProductoField = value;
                this.RaisePropertyChanged("precioProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public subtipoProducto subtipoProducto {
            get {
                return this.subtipoProductoField;
            }
            set {
                this.subtipoProductoField = value;
                this.RaisePropertyChanged("subtipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double tarificacion {
            get {
                return this.tarificacionField;
            }
            set {
                this.tarificacionField = value;
                this.RaisePropertyChanged("tarificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tarificacionSpecified {
            get {
                return this.tarificacionFieldSpecified;
            }
            set {
                this.tarificacionFieldSpecified = value;
                this.RaisePropertyChanged("tarificacionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findDetalleRequest() {
        }
        
        public findDetalleRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle @return;
        
        public findDetalleResponse() {
        }
        
        public findDetalleResponse(WSFAlimentos.SWDetalle.detalle @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle entity;
        
        public createDetalleRequest() {
        }
        
        public createDetalleRequest(WSFAlimentos.SWDetalle.detalle entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createDetalleResponse() {
        }
        
        public createDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle entity;
        
        public editDetalleRequest() {
        }
        
        public editDetalleRequest(WSFAlimentos.SWDetalle.detalle entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editDetalleResponse() {
        }
        
        public editDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle entity;
        
        public removeDetalleRequest() {
        }
        
        public removeDetalleRequest(WSFAlimentos.SWDetalle.detalle entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeDetalleResponse() {
        }
        
        public removeDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllDetalleRequest {
        
        public findAllDetalleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle[] @return;
        
        public findAllDetalleResponse() {
        }
        
        public findAllDetalleResponse(WSFAlimentos.SWDetalle.detalle[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeDetalleRequest() {
        }
        
        public findRangeDetalleRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWDetalle.detalle[] @return;
        
        public findRangeDetalleResponse() {
        }
        
        public findRangeDetalleResponse(WSFAlimentos.SWDetalle.detalle[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countDetalle", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countDetalleRequest {
        
        public countDetalleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countDetalleResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countDetalleResponse() {
        }
        
        public countDetalleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDetalle2", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createDetalle2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBoleta;
        
        public createDetalle2Request() {
        }
        
        public createDetalle2Request(int idProducto, int idBoleta) {
            this.idProducto = idProducto;
            this.idBoleta = idBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDetalle2Response", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createDetalle2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createDetalle2Response() {
        }
        
        public createDetalle2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDetalleChannel : WSFAlimentos.SWDetalle.WSDetalle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDetalleClient : System.ServiceModel.ClientBase<WSFAlimentos.SWDetalle.WSDetalle>, WSFAlimentos.SWDetalle.WSDetalle {
        
        public WSDetalleClient() {
        }
        
        public WSDetalleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDetalleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDetalleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDetalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.findDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.findDetalle(WSFAlimentos.SWDetalle.findDetalleRequest request) {
            return base.Channel.findDetalle(request);
        }
        
        public WSFAlimentos.SWDetalle.detalle findDetalle(int id) {
            WSFAlimentos.SWDetalle.findDetalleRequest inValue = new WSFAlimentos.SWDetalle.findDetalleRequest();
            inValue.id = id;
            WSFAlimentos.SWDetalle.findDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.findDetalleAsync(WSFAlimentos.SWDetalle.findDetalleRequest request) {
            return base.Channel.findDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findDetalleResponse> findDetalleAsync(int id) {
            WSFAlimentos.SWDetalle.findDetalleRequest inValue = new WSFAlimentos.SWDetalle.findDetalleRequest();
            inValue.id = id;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.createDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.createDetalle(WSFAlimentos.SWDetalle.createDetalleRequest request) {
            return base.Channel.createDetalle(request);
        }
        
        public bool createDetalle(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.createDetalleRequest inValue = new WSFAlimentos.SWDetalle.createDetalleRequest();
            inValue.entity = entity;
            WSFAlimentos.SWDetalle.createDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).createDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.createDetalleAsync(WSFAlimentos.SWDetalle.createDetalleRequest request) {
            return base.Channel.createDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalleResponse> createDetalleAsync(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.createDetalleRequest inValue = new WSFAlimentos.SWDetalle.createDetalleRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).createDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.editDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.editDetalle(WSFAlimentos.SWDetalle.editDetalleRequest request) {
            return base.Channel.editDetalle(request);
        }
        
        public bool editDetalle(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.editDetalleRequest inValue = new WSFAlimentos.SWDetalle.editDetalleRequest();
            inValue.entity = entity;
            WSFAlimentos.SWDetalle.editDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).editDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.editDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.editDetalleAsync(WSFAlimentos.SWDetalle.editDetalleRequest request) {
            return base.Channel.editDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.editDetalleResponse> editDetalleAsync(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.editDetalleRequest inValue = new WSFAlimentos.SWDetalle.editDetalleRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).editDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.removeDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.removeDetalle(WSFAlimentos.SWDetalle.removeDetalleRequest request) {
            return base.Channel.removeDetalle(request);
        }
        
        public bool removeDetalle(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.removeDetalleRequest inValue = new WSFAlimentos.SWDetalle.removeDetalleRequest();
            inValue.entity = entity;
            WSFAlimentos.SWDetalle.removeDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).removeDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.removeDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.removeDetalleAsync(WSFAlimentos.SWDetalle.removeDetalleRequest request) {
            return base.Channel.removeDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.removeDetalleResponse> removeDetalleAsync(WSFAlimentos.SWDetalle.detalle entity) {
            WSFAlimentos.SWDetalle.removeDetalleRequest inValue = new WSFAlimentos.SWDetalle.removeDetalleRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).removeDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.findAllDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.findAllDetalle(WSFAlimentos.SWDetalle.findAllDetalleRequest request) {
            return base.Channel.findAllDetalle(request);
        }
        
        public WSFAlimentos.SWDetalle.detalle[] findAllDetalle() {
            WSFAlimentos.SWDetalle.findAllDetalleRequest inValue = new WSFAlimentos.SWDetalle.findAllDetalleRequest();
            WSFAlimentos.SWDetalle.findAllDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findAllDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findAllDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.findAllDetalleAsync(WSFAlimentos.SWDetalle.findAllDetalleRequest request) {
            return base.Channel.findAllDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findAllDetalleResponse> findAllDetalleAsync() {
            WSFAlimentos.SWDetalle.findAllDetalleRequest inValue = new WSFAlimentos.SWDetalle.findAllDetalleRequest();
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findAllDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.findRangeDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.findRangeDetalle(WSFAlimentos.SWDetalle.findRangeDetalleRequest request) {
            return base.Channel.findRangeDetalle(request);
        }
        
        public WSFAlimentos.SWDetalle.detalle[] findRangeDetalle(System.Nullable<int>[] range) {
            WSFAlimentos.SWDetalle.findRangeDetalleRequest inValue = new WSFAlimentos.SWDetalle.findRangeDetalleRequest();
            inValue.range = range;
            WSFAlimentos.SWDetalle.findRangeDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findRangeDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findRangeDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.findRangeDetalleAsync(WSFAlimentos.SWDetalle.findRangeDetalleRequest request) {
            return base.Channel.findRangeDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.findRangeDetalleResponse> findRangeDetalleAsync(System.Nullable<int>[] range) {
            WSFAlimentos.SWDetalle.findRangeDetalleRequest inValue = new WSFAlimentos.SWDetalle.findRangeDetalleRequest();
            inValue.range = range;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).findRangeDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.countDetalleResponse WSFAlimentos.SWDetalle.WSDetalle.countDetalle(WSFAlimentos.SWDetalle.countDetalleRequest request) {
            return base.Channel.countDetalle(request);
        }
        
        public int countDetalle() {
            WSFAlimentos.SWDetalle.countDetalleRequest inValue = new WSFAlimentos.SWDetalle.countDetalleRequest();
            WSFAlimentos.SWDetalle.countDetalleResponse retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).countDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.countDetalleResponse> WSFAlimentos.SWDetalle.WSDetalle.countDetalleAsync(WSFAlimentos.SWDetalle.countDetalleRequest request) {
            return base.Channel.countDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.countDetalleResponse> countDetalleAsync() {
            WSFAlimentos.SWDetalle.countDetalleRequest inValue = new WSFAlimentos.SWDetalle.countDetalleRequest();
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).countDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWDetalle.createDetalle2Response WSFAlimentos.SWDetalle.WSDetalle.createDetalle2(WSFAlimentos.SWDetalle.createDetalle2Request request) {
            return base.Channel.createDetalle2(request);
        }
        
        public bool createDetalle2(int idProducto, int idBoleta) {
            WSFAlimentos.SWDetalle.createDetalle2Request inValue = new WSFAlimentos.SWDetalle.createDetalle2Request();
            inValue.idProducto = idProducto;
            inValue.idBoleta = idBoleta;
            WSFAlimentos.SWDetalle.createDetalle2Response retVal = ((WSFAlimentos.SWDetalle.WSDetalle)(this)).createDetalle2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalle2Response> WSFAlimentos.SWDetalle.WSDetalle.createDetalle2Async(WSFAlimentos.SWDetalle.createDetalle2Request request) {
            return base.Channel.createDetalle2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWDetalle.createDetalle2Response> createDetalle2Async(int idProducto, int idBoleta) {
            WSFAlimentos.SWDetalle.createDetalle2Request inValue = new WSFAlimentos.SWDetalle.createDetalle2Request();
            inValue.idProducto = idProducto;
            inValue.idBoleta = idBoleta;
            return ((WSFAlimentos.SWDetalle.WSDetalle)(this)).createDetalle2Async(inValue);
        }
    }
}
