//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAlimentos.SWVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWVenta.WSVentas")]
    public interface WSVentas {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findVentasRequest", ReplyAction="http://service/WSVentas/findVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.findVentasResponse findVentas(WSFAlimentos.SWVenta.findVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findVentasRequest", ReplyAction="http://service/WSVentas/findVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findVentasResponse> findVentasAsync(WSFAlimentos.SWVenta.findVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/createVentasRequest", ReplyAction="http://service/WSVentas/createVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.createVentasResponse createVentas(WSFAlimentos.SWVenta.createVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/createVentasRequest", ReplyAction="http://service/WSVentas/createVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.createVentasResponse> createVentasAsync(WSFAlimentos.SWVenta.createVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/editVentasRequest", ReplyAction="http://service/WSVentas/editVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.editVentasResponse editVentas(WSFAlimentos.SWVenta.editVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/editVentasRequest", ReplyAction="http://service/WSVentas/editVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.editVentasResponse> editVentasAsync(WSFAlimentos.SWVenta.editVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/removeVentasRequest", ReplyAction="http://service/WSVentas/removeVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.removeVentasResponse removeVentas(WSFAlimentos.SWVenta.removeVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/removeVentasRequest", ReplyAction="http://service/WSVentas/removeVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.removeVentasResponse> removeVentasAsync(WSFAlimentos.SWVenta.removeVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findAllVentasRequest", ReplyAction="http://service/WSVentas/findAllVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.findAllVentasResponse findAllVentas(WSFAlimentos.SWVenta.findAllVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findAllVentasRequest", ReplyAction="http://service/WSVentas/findAllVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findAllVentasResponse> findAllVentasAsync(WSFAlimentos.SWVenta.findAllVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findRangeVentasRequest", ReplyAction="http://service/WSVentas/findRangeVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.findRangeVentasResponse findRangeVentas(WSFAlimentos.SWVenta.findRangeVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/findRangeVentasRequest", ReplyAction="http://service/WSVentas/findRangeVentasResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findRangeVentasResponse> findRangeVentasAsync(WSFAlimentos.SWVenta.findRangeVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/countRequest", ReplyAction="http://service/WSVentas/countResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.countResponse count(WSFAlimentos.SWVenta.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/countRequest", ReplyAction="http://service/WSVentas/countResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.countResponse> countAsync(WSFAlimentos.SWVenta.countRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/CrearVenta2Request", ReplyAction="http://service/WSVentas/CrearVenta2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWVenta.CrearVenta2Response CrearVenta2(WSFAlimentos.SWVenta.CrearVenta2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVentas/CrearVenta2Request", ReplyAction="http://service/WSVentas/CrearVenta2Response")]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.CrearVenta2Response> CrearVenta2Async(WSFAlimentos.SWVenta.CrearVenta2Request request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class ventas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoVField;
        
        private cliente clienteIdClienteField;
        
        private System.DateTime fechaEntregaField;
        
        private bool fechaEntregaFieldSpecified;
        
        private System.DateTime fechaVentaField;
        
        private bool fechaVentaFieldSpecified;
        
        private int idventasField;
        
        private bool idventasFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoV {
            get {
                return this.activoVField;
            }
            set {
                this.activoVField = value;
                this.RaisePropertyChanged("activoV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente clienteIdCliente {
            get {
                return this.clienteIdClienteField;
            }
            set {
                this.clienteIdClienteField = value;
                this.RaisePropertyChanged("clienteIdCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEntregaSpecified {
            get {
                return this.fechaEntregaFieldSpecified;
            }
            set {
                this.fechaEntregaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEntregaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVenta {
            get {
                return this.fechaVentaField;
            }
            set {
                this.fechaVentaField = value;
                this.RaisePropertyChanged("fechaVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVentaSpecified {
            get {
                return this.fechaVentaFieldSpecified;
            }
            set {
                this.fechaVentaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVentaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idventas {
            get {
                return this.idventasField;
            }
            set {
                this.idventasField = value;
                this.RaisePropertyChanged("idventas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idventasSpecified {
            get {
                return this.idventasFieldSpecified;
            }
            set {
                this.idventasFieldSpecified = value;
                this.RaisePropertyChanged("idventasSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoCField;
        
        private string apellidoClienteField;
        
        private string dvField;
        
        private int edadClienteField;
        
        private estadoCivil estadoCivilIdEstadoCivilField;
        
        private short idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private string nombreClienteField;
        
        private int rutField;
        
        private bool sexoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoC {
            get {
                return this.activoCField;
            }
            set {
                this.activoCField = value;
                this.RaisePropertyChanged("activoC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoCliente {
            get {
                return this.apellidoClienteField;
            }
            set {
                this.apellidoClienteField = value;
                this.RaisePropertyChanged("apellidoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edadCliente {
            get {
                return this.edadClienteField;
            }
            set {
                this.edadClienteField = value;
                this.RaisePropertyChanged("edadCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoCivil estadoCivilIdEstadoCivil {
            get {
                return this.estadoCivilIdEstadoCivilField;
            }
            set {
                this.estadoCivilIdEstadoCivilField = value;
                this.RaisePropertyChanged("estadoCivilIdEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class estadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEstadoCivilField;
        
        private short idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEstadoCivil {
            get {
                return this.descripcionEstadoCivilField;
            }
            set {
                this.descripcionEstadoCivilField = value;
                this.RaisePropertyChanged("descripcionEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findVentasRequest() {
        }
        
        public findVentasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas @return;
        
        public findVentasResponse() {
        }
        
        public findVentasResponse(WSFAlimentos.SWVenta.ventas @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas entity;
        
        public createVentasRequest() {
        }
        
        public createVentasRequest(WSFAlimentos.SWVenta.ventas entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createVentasResponse() {
        }
        
        public createVentasResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas entity;
        
        public editVentasRequest() {
        }
        
        public editVentasRequest(WSFAlimentos.SWVenta.ventas entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editVentasResponse() {
        }
        
        public editVentasResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas entity;
        
        public removeVentasRequest() {
        }
        
        public removeVentasRequest(WSFAlimentos.SWVenta.ventas entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeVentasResponse() {
        }
        
        public removeVentasResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllVentasRequest {
        
        public findAllVentasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas[] @return;
        
        public findAllVentasResponse() {
        }
        
        public findAllVentasResponse(WSFAlimentos.SWVenta.ventas[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeVentas", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeVentasRequest() {
        }
        
        public findRangeVentasRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeVentasResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWVenta.ventas[] @return;
        
        public findRangeVentasResponse() {
        }
        
        public findRangeVentasResponse(WSFAlimentos.SWVenta.ventas[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="count", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countRequest {
        
        public countRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countResponse() {
        }
        
        public countResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearVenta2", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CrearVenta2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        public CrearVenta2Request() {
        }
        
        public CrearVenta2Request(bool activo, System.DateTime fechaE, string dv, int rut) {
            this.activo = activo;
            this.fechaE = fechaE;
            this.dv = dv;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearVenta2Response", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CrearVenta2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public CrearVenta2Response() {
        }
        
        public CrearVenta2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSVentasChannel : WSFAlimentos.SWVenta.WSVentas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSVentasClient : System.ServiceModel.ClientBase<WSFAlimentos.SWVenta.WSVentas>, WSFAlimentos.SWVenta.WSVentas {
        
        public WSVentasClient() {
        }
        
        public WSVentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSVentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.findVentasResponse WSFAlimentos.SWVenta.WSVentas.findVentas(WSFAlimentos.SWVenta.findVentasRequest request) {
            return base.Channel.findVentas(request);
        }
        
        public WSFAlimentos.SWVenta.ventas findVentas(int id) {
            WSFAlimentos.SWVenta.findVentasRequest inValue = new WSFAlimentos.SWVenta.findVentasRequest();
            inValue.id = id;
            WSFAlimentos.SWVenta.findVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).findVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findVentasResponse> WSFAlimentos.SWVenta.WSVentas.findVentasAsync(WSFAlimentos.SWVenta.findVentasRequest request) {
            return base.Channel.findVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findVentasResponse> findVentasAsync(int id) {
            WSFAlimentos.SWVenta.findVentasRequest inValue = new WSFAlimentos.SWVenta.findVentasRequest();
            inValue.id = id;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).findVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.createVentasResponse WSFAlimentos.SWVenta.WSVentas.createVentas(WSFAlimentos.SWVenta.createVentasRequest request) {
            return base.Channel.createVentas(request);
        }
        
        public bool createVentas(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.createVentasRequest inValue = new WSFAlimentos.SWVenta.createVentasRequest();
            inValue.entity = entity;
            WSFAlimentos.SWVenta.createVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).createVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.createVentasResponse> WSFAlimentos.SWVenta.WSVentas.createVentasAsync(WSFAlimentos.SWVenta.createVentasRequest request) {
            return base.Channel.createVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.createVentasResponse> createVentasAsync(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.createVentasRequest inValue = new WSFAlimentos.SWVenta.createVentasRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).createVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.editVentasResponse WSFAlimentos.SWVenta.WSVentas.editVentas(WSFAlimentos.SWVenta.editVentasRequest request) {
            return base.Channel.editVentas(request);
        }
        
        public bool editVentas(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.editVentasRequest inValue = new WSFAlimentos.SWVenta.editVentasRequest();
            inValue.entity = entity;
            WSFAlimentos.SWVenta.editVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).editVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.editVentasResponse> WSFAlimentos.SWVenta.WSVentas.editVentasAsync(WSFAlimentos.SWVenta.editVentasRequest request) {
            return base.Channel.editVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.editVentasResponse> editVentasAsync(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.editVentasRequest inValue = new WSFAlimentos.SWVenta.editVentasRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).editVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.removeVentasResponse WSFAlimentos.SWVenta.WSVentas.removeVentas(WSFAlimentos.SWVenta.removeVentasRequest request) {
            return base.Channel.removeVentas(request);
        }
        
        public bool removeVentas(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.removeVentasRequest inValue = new WSFAlimentos.SWVenta.removeVentasRequest();
            inValue.entity = entity;
            WSFAlimentos.SWVenta.removeVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).removeVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.removeVentasResponse> WSFAlimentos.SWVenta.WSVentas.removeVentasAsync(WSFAlimentos.SWVenta.removeVentasRequest request) {
            return base.Channel.removeVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.removeVentasResponse> removeVentasAsync(WSFAlimentos.SWVenta.ventas entity) {
            WSFAlimentos.SWVenta.removeVentasRequest inValue = new WSFAlimentos.SWVenta.removeVentasRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).removeVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.findAllVentasResponse WSFAlimentos.SWVenta.WSVentas.findAllVentas(WSFAlimentos.SWVenta.findAllVentasRequest request) {
            return base.Channel.findAllVentas(request);
        }
        
        public WSFAlimentos.SWVenta.ventas[] findAllVentas() {
            WSFAlimentos.SWVenta.findAllVentasRequest inValue = new WSFAlimentos.SWVenta.findAllVentasRequest();
            WSFAlimentos.SWVenta.findAllVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).findAllVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findAllVentasResponse> WSFAlimentos.SWVenta.WSVentas.findAllVentasAsync(WSFAlimentos.SWVenta.findAllVentasRequest request) {
            return base.Channel.findAllVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findAllVentasResponse> findAllVentasAsync() {
            WSFAlimentos.SWVenta.findAllVentasRequest inValue = new WSFAlimentos.SWVenta.findAllVentasRequest();
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).findAllVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.findRangeVentasResponse WSFAlimentos.SWVenta.WSVentas.findRangeVentas(WSFAlimentos.SWVenta.findRangeVentasRequest request) {
            return base.Channel.findRangeVentas(request);
        }
        
        public WSFAlimentos.SWVenta.ventas[] findRangeVentas(System.Nullable<int>[] range) {
            WSFAlimentos.SWVenta.findRangeVentasRequest inValue = new WSFAlimentos.SWVenta.findRangeVentasRequest();
            inValue.range = range;
            WSFAlimentos.SWVenta.findRangeVentasResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).findRangeVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findRangeVentasResponse> WSFAlimentos.SWVenta.WSVentas.findRangeVentasAsync(WSFAlimentos.SWVenta.findRangeVentasRequest request) {
            return base.Channel.findRangeVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.findRangeVentasResponse> findRangeVentasAsync(System.Nullable<int>[] range) {
            WSFAlimentos.SWVenta.findRangeVentasRequest inValue = new WSFAlimentos.SWVenta.findRangeVentasRequest();
            inValue.range = range;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).findRangeVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.countResponse WSFAlimentos.SWVenta.WSVentas.count(WSFAlimentos.SWVenta.countRequest request) {
            return base.Channel.count(request);
        }
        
        public int count() {
            WSFAlimentos.SWVenta.countRequest inValue = new WSFAlimentos.SWVenta.countRequest();
            WSFAlimentos.SWVenta.countResponse retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).count(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.countResponse> WSFAlimentos.SWVenta.WSVentas.countAsync(WSFAlimentos.SWVenta.countRequest request) {
            return base.Channel.countAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.countResponse> countAsync() {
            WSFAlimentos.SWVenta.countRequest inValue = new WSFAlimentos.SWVenta.countRequest();
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).countAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWVenta.CrearVenta2Response WSFAlimentos.SWVenta.WSVentas.CrearVenta2(WSFAlimentos.SWVenta.CrearVenta2Request request) {
            return base.Channel.CrearVenta2(request);
        }
        
        public bool CrearVenta2(bool activo, System.DateTime fechaE, string dv, int rut) {
            WSFAlimentos.SWVenta.CrearVenta2Request inValue = new WSFAlimentos.SWVenta.CrearVenta2Request();
            inValue.activo = activo;
            inValue.fechaE = fechaE;
            inValue.dv = dv;
            inValue.rut = rut;
            WSFAlimentos.SWVenta.CrearVenta2Response retVal = ((WSFAlimentos.SWVenta.WSVentas)(this)).CrearVenta2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWVenta.CrearVenta2Response> WSFAlimentos.SWVenta.WSVentas.CrearVenta2Async(WSFAlimentos.SWVenta.CrearVenta2Request request) {
            return base.Channel.CrearVenta2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWVenta.CrearVenta2Response> CrearVenta2Async(bool activo, System.DateTime fechaE, string dv, int rut) {
            WSFAlimentos.SWVenta.CrearVenta2Request inValue = new WSFAlimentos.SWVenta.CrearVenta2Request();
            inValue.activo = activo;
            inValue.fechaE = fechaE;
            inValue.dv = dv;
            inValue.rut = rut;
            return ((WSFAlimentos.SWVenta.WSVentas)(this)).CrearVenta2Async(inValue);
        }
    }
}
