//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAlimentos.SWEstadoCivil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWEstadoCivil.WSEstadoCivil")]
    public interface WSEstadoCivil {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/createEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/createEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse createEstadoCivil(WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/createEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/createEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse> createEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/removeEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/removeEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse removeEstadoCivil(WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/removeEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/removeEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse> removeEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findAllEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findAllEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse findAllEstadoCivil(WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findAllEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findAllEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse> findAllEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findRangeEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findRangeEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse findRangeEstadoCivil(WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findRangeEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findRangeEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse> findRangeEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/editEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/editEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse editEstadoCivil(WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/editEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/editEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse> editEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse findEstadoCivil(WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/findEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/findEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse> findEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/countEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/countEstadoCivilResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse countEstadoCivil(WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSEstadoCivil/countEstadoCivilRequest", ReplyAction="http://service/WSEstadoCivil/countEstadoCivilResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse> countEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class estadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEstadoCivilField;
        
        private short idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEstadoCivil {
            get {
                return this.descripcionEstadoCivilField;
            }
            set {
                this.descripcionEstadoCivilField = value;
                this.RaisePropertyChanged("descripcionEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createEstadoCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil entity;
        
        public createEstadoCivilRequest() {
        }
        
        public createEstadoCivilRequest(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createEstadoCivilResponse() {
        }
        
        public createEstadoCivilResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeEstadoCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil entity;
        
        public removeEstadoCivilRequest() {
        }
        
        public removeEstadoCivilRequest(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeEstadoCivilResponse() {
        }
        
        public removeEstadoCivilResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllEstadoCivilRequest {
        
        public findAllEstadoCivilRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil[] @return;
        
        public findAllEstadoCivilResponse() {
        }
        
        public findAllEstadoCivilResponse(WSFAlimentos.SWEstadoCivil.estadoCivil[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeEstadoCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeEstadoCivilRequest() {
        }
        
        public findRangeEstadoCivilRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil[] @return;
        
        public findRangeEstadoCivilResponse() {
        }
        
        public findRangeEstadoCivilResponse(WSFAlimentos.SWEstadoCivil.estadoCivil[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editEstadoCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil entity;
        
        public editEstadoCivilRequest() {
        }
        
        public editEstadoCivilRequest(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editEstadoCivilResponse() {
        }
        
        public editEstadoCivilResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findEstadoCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findEstadoCivilRequest() {
        }
        
        public findEstadoCivilRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWEstadoCivil.estadoCivil @return;
        
        public findEstadoCivilResponse() {
        }
        
        public findEstadoCivilResponse(WSFAlimentos.SWEstadoCivil.estadoCivil @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countEstadoCivil", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countEstadoCivilRequest {
        
        public countEstadoCivilRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countEstadoCivilResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countEstadoCivilResponse() {
        }
        
        public countEstadoCivilResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEstadoCivilChannel : WSFAlimentos.SWEstadoCivil.WSEstadoCivil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEstadoCivilClient : System.ServiceModel.ClientBase<WSFAlimentos.SWEstadoCivil.WSEstadoCivil>, WSFAlimentos.SWEstadoCivil.WSEstadoCivil {
        
        public WSEstadoCivilClient() {
        }
        
        public WSEstadoCivilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEstadoCivilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEstadoCivilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEstadoCivilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.createEstadoCivil(WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest request) {
            return base.Channel.createEstadoCivil(request);
        }
        
        public bool createEstadoCivil(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest();
            inValue.entity = entity;
            WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).createEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.createEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest request) {
            return base.Channel.createEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.createEstadoCivilResponse> createEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.createEstadoCivilRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).createEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.removeEstadoCivil(WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest request) {
            return base.Channel.removeEstadoCivil(request);
        }
        
        public bool removeEstadoCivil(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest();
            inValue.entity = entity;
            WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).removeEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.removeEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest request) {
            return base.Channel.removeEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.removeEstadoCivilResponse> removeEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.removeEstadoCivilRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).removeEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findAllEstadoCivil(WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest request) {
            return base.Channel.findAllEstadoCivil(request);
        }
        
        public WSFAlimentos.SWEstadoCivil.estadoCivil[] findAllEstadoCivil() {
            WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest();
            WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findAllEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findAllEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest request) {
            return base.Channel.findAllEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findAllEstadoCivilResponse> findAllEstadoCivilAsync() {
            WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findAllEstadoCivilRequest();
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findAllEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findRangeEstadoCivil(WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest request) {
            return base.Channel.findRangeEstadoCivil(request);
        }
        
        public WSFAlimentos.SWEstadoCivil.estadoCivil[] findRangeEstadoCivil(System.Nullable<int>[] range) {
            WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest();
            inValue.range = range;
            WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findRangeEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findRangeEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest request) {
            return base.Channel.findRangeEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilResponse> findRangeEstadoCivilAsync(System.Nullable<int>[] range) {
            WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findRangeEstadoCivilRequest();
            inValue.range = range;
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findRangeEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.editEstadoCivil(WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest request) {
            return base.Channel.editEstadoCivil(request);
        }
        
        public bool editEstadoCivil(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest();
            inValue.entity = entity;
            WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).editEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.editEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest request) {
            return base.Channel.editEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.editEstadoCivilResponse> editEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.estadoCivil entity) {
            WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.editEstadoCivilRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).editEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findEstadoCivil(WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest request) {
            return base.Channel.findEstadoCivil(request);
        }
        
        public WSFAlimentos.SWEstadoCivil.estadoCivil findEstadoCivil(int id) {
            WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest();
            inValue.id = id;
            WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.findEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest request) {
            return base.Channel.findEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.findEstadoCivilResponse> findEstadoCivilAsync(int id) {
            WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.findEstadoCivilRequest();
            inValue.id = id;
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).findEstadoCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse WSFAlimentos.SWEstadoCivil.WSEstadoCivil.countEstadoCivil(WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest request) {
            return base.Channel.countEstadoCivil(request);
        }
        
        public int countEstadoCivil() {
            WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest();
            WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse retVal = ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).countEstadoCivil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse> WSFAlimentos.SWEstadoCivil.WSEstadoCivil.countEstadoCivilAsync(WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest request) {
            return base.Channel.countEstadoCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWEstadoCivil.countEstadoCivilResponse> countEstadoCivilAsync() {
            WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest inValue = new WSFAlimentos.SWEstadoCivil.countEstadoCivilRequest();
            return ((WSFAlimentos.SWEstadoCivil.WSEstadoCivil)(this)).countEstadoCivilAsync(inValue);
        }
    }
}
