//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAlimentos.SWProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWProducto.WSProducto")]
    public interface WSProducto {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findRangeProductoRequest", ReplyAction="http://service/WSProducto/findRangeProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.findRangeProductoResponse findRangeProducto(WSFAlimentos.SWProducto.findRangeProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findRangeProductoRequest", ReplyAction="http://service/WSProducto/findRangeProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findRangeProductoResponse> findRangeProductoAsync(WSFAlimentos.SWProducto.findRangeProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findProductoRequest", ReplyAction="http://service/WSProducto/findProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.findProductoResponse findProducto(WSFAlimentos.SWProducto.findProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findProductoRequest", ReplyAction="http://service/WSProducto/findProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findProductoResponse> findProductoAsync(WSFAlimentos.SWProducto.findProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/createProductoRequest", ReplyAction="http://service/WSProducto/createProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.createProductoResponse createProducto(WSFAlimentos.SWProducto.createProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/createProductoRequest", ReplyAction="http://service/WSProducto/createProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.createProductoResponse> createProductoAsync(WSFAlimentos.SWProducto.createProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/editProductoRequest", ReplyAction="http://service/WSProducto/editProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.editProductoResponse editProducto(WSFAlimentos.SWProducto.editProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/editProductoRequest", ReplyAction="http://service/WSProducto/editProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.editProductoResponse> editProductoAsync(WSFAlimentos.SWProducto.editProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/removeProductoRequest", ReplyAction="http://service/WSProducto/removeProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.removeProductoResponse removeProducto(WSFAlimentos.SWProducto.removeProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/removeProductoRequest", ReplyAction="http://service/WSProducto/removeProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.removeProductoResponse> removeProductoAsync(WSFAlimentos.SWProducto.removeProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findAllProductoRequest", ReplyAction="http://service/WSProducto/findAllProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.findAllProductoResponse findAllProducto(WSFAlimentos.SWProducto.findAllProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/findAllProductoRequest", ReplyAction="http://service/WSProducto/findAllProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findAllProductoResponse> findAllProductoAsync(WSFAlimentos.SWProducto.findAllProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/countProductoRequest", ReplyAction="http://service/WSProducto/countProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.countProductoResponse countProducto(WSFAlimentos.SWProducto.countProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/countProductoRequest", ReplyAction="http://service/WSProducto/countProductoResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.countProductoResponse> countProductoAsync(WSFAlimentos.SWProducto.countProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/CreateProducto2Request", ReplyAction="http://service/WSProducto/CreateProducto2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWProducto.CreateProducto2Response CreateProducto2(WSFAlimentos.SWProducto.CreateProducto2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSProducto/CreateProducto2Request", ReplyAction="http://service/WSProducto/CreateProducto2Response")]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.CreateProducto2Response> CreateProducto2Async(WSFAlimentos.SWProducto.CreateProducto2Request request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime anioFField;
        
        private bool anioFFieldSpecified;
        
        private System.DateTime anioVField;
        
        private bool anioVFieldSpecified;
        
        private string descripcionProductoField;
        
        private short idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string nombreProductoField;
        
        private int precioProductoField;
        
        private int stockField;
        
        private subtipoProducto subtipoProductoField;
        
        private double tarificacionField;
        
        private bool tarificacionFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime anioF {
            get {
                return this.anioFField;
            }
            set {
                this.anioFField = value;
                this.RaisePropertyChanged("anioF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioFSpecified {
            get {
                return this.anioFFieldSpecified;
            }
            set {
                this.anioFFieldSpecified = value;
                this.RaisePropertyChanged("anioFSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime anioV {
            get {
                return this.anioVField;
            }
            set {
                this.anioVField = value;
                this.RaisePropertyChanged("anioV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioVSpecified {
            get {
                return this.anioVFieldSpecified;
            }
            set {
                this.anioVFieldSpecified = value;
                this.RaisePropertyChanged("anioVSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
                this.RaisePropertyChanged("descripcionProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                this.precioProductoField = value;
                this.RaisePropertyChanged("precioProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public subtipoProducto subtipoProducto {
            get {
                return this.subtipoProductoField;
            }
            set {
                this.subtipoProductoField = value;
                this.RaisePropertyChanged("subtipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double tarificacion {
            get {
                return this.tarificacionField;
            }
            set {
                this.tarificacionField = value;
                this.RaisePropertyChanged("tarificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tarificacionSpecified {
            get {
                return this.tarificacionFieldSpecified;
            }
            set {
                this.tarificacionFieldSpecified = value;
                this.RaisePropertyChanged("tarificacionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class subtipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionStpField;
        
        private subtipoProductoPK subtipoProductoPKField;
        
        private tipoProducto tipoProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionStp {
            get {
                return this.descripcionStpField;
            }
            set {
                this.descripcionStpField = value;
                this.RaisePropertyChanged("descripcionStp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public subtipoProductoPK subtipoProductoPK {
            get {
                return this.subtipoProductoPKField;
            }
            set {
                this.subtipoProductoPKField = value;
                this.RaisePropertyChanged("subtipoProductoPK");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class subtipoProductoPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short subtipoPField;
        
        private short tipoProductoIdTpField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short subtipoP {
            get {
                return this.subtipoPField;
            }
            set {
                this.subtipoPField = value;
                this.RaisePropertyChanged("subtipoP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short tipoProductoIdTp {
            get {
                return this.tipoProductoIdTpField;
            }
            set {
                this.tipoProductoIdTpField = value;
                this.RaisePropertyChanged("tipoProductoIdTp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class tipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionTpField;
        
        private short idTpField;
        
        private bool idTpFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionTp {
            get {
                return this.descripcionTpField;
            }
            set {
                this.descripcionTpField = value;
                this.RaisePropertyChanged("descripcionTp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
                this.RaisePropertyChanged("idTp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTpSpecified {
            get {
                return this.idTpFieldSpecified;
            }
            set {
                this.idTpFieldSpecified = value;
                this.RaisePropertyChanged("idTpSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeProductoRequest() {
        }
        
        public findRangeProductoRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto[] @return;
        
        public findRangeProductoResponse() {
        }
        
        public findRangeProductoResponse(WSFAlimentos.SWProducto.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findProductoRequest() {
        }
        
        public findProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto @return;
        
        public findProductoResponse() {
        }
        
        public findProductoResponse(WSFAlimentos.SWProducto.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto entity;
        
        public createProductoRequest() {
        }
        
        public createProductoRequest(WSFAlimentos.SWProducto.producto entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createProductoResponse() {
        }
        
        public createProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto entity;
        
        public editProductoRequest() {
        }
        
        public editProductoRequest(WSFAlimentos.SWProducto.producto entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editProductoResponse() {
        }
        
        public editProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto entity;
        
        public removeProductoRequest() {
        }
        
        public removeProductoRequest(WSFAlimentos.SWProducto.producto entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeProductoResponse() {
        }
        
        public removeProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllProductoRequest {
        
        public findAllProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWProducto.producto[] @return;
        
        public findAllProductoResponse() {
        }
        
        public findAllProductoResponse(WSFAlimentos.SWProducto.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countProducto", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countProductoRequest {
        
        public countProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countProductoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countProductoResponse() {
        }
        
        public countProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProducto2", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateProducto2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime anioF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime anioV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double tarifa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSubTipo;
        
        public CreateProducto2Request() {
        }
        
        public CreateProducto2Request(string nombre, int precio, System.DateTime anioF, System.DateTime anioV, string descripcion, int stock, double tarifa, int idSubTipo) {
            this.nombre = nombre;
            this.precio = precio;
            this.anioF = anioF;
            this.anioV = anioV;
            this.descripcion = descripcion;
            this.stock = stock;
            this.tarifa = tarifa;
            this.idSubTipo = idSubTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProducto2Response", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateProducto2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public CreateProducto2Response() {
        }
        
        public CreateProducto2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProductoChannel : WSFAlimentos.SWProducto.WSProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProductoClient : System.ServiceModel.ClientBase<WSFAlimentos.SWProducto.WSProducto>, WSFAlimentos.SWProducto.WSProducto {
        
        public WSProductoClient() {
        }
        
        public WSProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.findRangeProductoResponse WSFAlimentos.SWProducto.WSProducto.findRangeProducto(WSFAlimentos.SWProducto.findRangeProductoRequest request) {
            return base.Channel.findRangeProducto(request);
        }
        
        public WSFAlimentos.SWProducto.producto[] findRangeProducto(System.Nullable<int>[] range) {
            WSFAlimentos.SWProducto.findRangeProductoRequest inValue = new WSFAlimentos.SWProducto.findRangeProductoRequest();
            inValue.range = range;
            WSFAlimentos.SWProducto.findRangeProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).findRangeProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findRangeProductoResponse> WSFAlimentos.SWProducto.WSProducto.findRangeProductoAsync(WSFAlimentos.SWProducto.findRangeProductoRequest request) {
            return base.Channel.findRangeProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findRangeProductoResponse> findRangeProductoAsync(System.Nullable<int>[] range) {
            WSFAlimentos.SWProducto.findRangeProductoRequest inValue = new WSFAlimentos.SWProducto.findRangeProductoRequest();
            inValue.range = range;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).findRangeProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.findProductoResponse WSFAlimentos.SWProducto.WSProducto.findProducto(WSFAlimentos.SWProducto.findProductoRequest request) {
            return base.Channel.findProducto(request);
        }
        
        public WSFAlimentos.SWProducto.producto findProducto(int id) {
            WSFAlimentos.SWProducto.findProductoRequest inValue = new WSFAlimentos.SWProducto.findProductoRequest();
            inValue.id = id;
            WSFAlimentos.SWProducto.findProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).findProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findProductoResponse> WSFAlimentos.SWProducto.WSProducto.findProductoAsync(WSFAlimentos.SWProducto.findProductoRequest request) {
            return base.Channel.findProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findProductoResponse> findProductoAsync(int id) {
            WSFAlimentos.SWProducto.findProductoRequest inValue = new WSFAlimentos.SWProducto.findProductoRequest();
            inValue.id = id;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).findProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.createProductoResponse WSFAlimentos.SWProducto.WSProducto.createProducto(WSFAlimentos.SWProducto.createProductoRequest request) {
            return base.Channel.createProducto(request);
        }
        
        public bool createProducto(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.createProductoRequest inValue = new WSFAlimentos.SWProducto.createProductoRequest();
            inValue.entity = entity;
            WSFAlimentos.SWProducto.createProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).createProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.createProductoResponse> WSFAlimentos.SWProducto.WSProducto.createProductoAsync(WSFAlimentos.SWProducto.createProductoRequest request) {
            return base.Channel.createProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.createProductoResponse> createProductoAsync(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.createProductoRequest inValue = new WSFAlimentos.SWProducto.createProductoRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).createProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.editProductoResponse WSFAlimentos.SWProducto.WSProducto.editProducto(WSFAlimentos.SWProducto.editProductoRequest request) {
            return base.Channel.editProducto(request);
        }
        
        public bool editProducto(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.editProductoRequest inValue = new WSFAlimentos.SWProducto.editProductoRequest();
            inValue.entity = entity;
            WSFAlimentos.SWProducto.editProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).editProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.editProductoResponse> WSFAlimentos.SWProducto.WSProducto.editProductoAsync(WSFAlimentos.SWProducto.editProductoRequest request) {
            return base.Channel.editProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.editProductoResponse> editProductoAsync(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.editProductoRequest inValue = new WSFAlimentos.SWProducto.editProductoRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).editProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.removeProductoResponse WSFAlimentos.SWProducto.WSProducto.removeProducto(WSFAlimentos.SWProducto.removeProductoRequest request) {
            return base.Channel.removeProducto(request);
        }
        
        public bool removeProducto(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.removeProductoRequest inValue = new WSFAlimentos.SWProducto.removeProductoRequest();
            inValue.entity = entity;
            WSFAlimentos.SWProducto.removeProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).removeProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.removeProductoResponse> WSFAlimentos.SWProducto.WSProducto.removeProductoAsync(WSFAlimentos.SWProducto.removeProductoRequest request) {
            return base.Channel.removeProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.removeProductoResponse> removeProductoAsync(WSFAlimentos.SWProducto.producto entity) {
            WSFAlimentos.SWProducto.removeProductoRequest inValue = new WSFAlimentos.SWProducto.removeProductoRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).removeProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.findAllProductoResponse WSFAlimentos.SWProducto.WSProducto.findAllProducto(WSFAlimentos.SWProducto.findAllProductoRequest request) {
            return base.Channel.findAllProducto(request);
        }
        
        public WSFAlimentos.SWProducto.producto[] findAllProducto() {
            WSFAlimentos.SWProducto.findAllProductoRequest inValue = new WSFAlimentos.SWProducto.findAllProductoRequest();
            WSFAlimentos.SWProducto.findAllProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).findAllProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findAllProductoResponse> WSFAlimentos.SWProducto.WSProducto.findAllProductoAsync(WSFAlimentos.SWProducto.findAllProductoRequest request) {
            return base.Channel.findAllProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.findAllProductoResponse> findAllProductoAsync() {
            WSFAlimentos.SWProducto.findAllProductoRequest inValue = new WSFAlimentos.SWProducto.findAllProductoRequest();
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).findAllProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.countProductoResponse WSFAlimentos.SWProducto.WSProducto.countProducto(WSFAlimentos.SWProducto.countProductoRequest request) {
            return base.Channel.countProducto(request);
        }
        
        public int countProducto() {
            WSFAlimentos.SWProducto.countProductoRequest inValue = new WSFAlimentos.SWProducto.countProductoRequest();
            WSFAlimentos.SWProducto.countProductoResponse retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).countProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.countProductoResponse> WSFAlimentos.SWProducto.WSProducto.countProductoAsync(WSFAlimentos.SWProducto.countProductoRequest request) {
            return base.Channel.countProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.countProductoResponse> countProductoAsync() {
            WSFAlimentos.SWProducto.countProductoRequest inValue = new WSFAlimentos.SWProducto.countProductoRequest();
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).countProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWProducto.CreateProducto2Response WSFAlimentos.SWProducto.WSProducto.CreateProducto2(WSFAlimentos.SWProducto.CreateProducto2Request request) {
            return base.Channel.CreateProducto2(request);
        }
        
        public bool CreateProducto2(string nombre, int precio, System.DateTime anioF, System.DateTime anioV, string descripcion, int stock, double tarifa, int idSubTipo) {
            WSFAlimentos.SWProducto.CreateProducto2Request inValue = new WSFAlimentos.SWProducto.CreateProducto2Request();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.anioF = anioF;
            inValue.anioV = anioV;
            inValue.descripcion = descripcion;
            inValue.stock = stock;
            inValue.tarifa = tarifa;
            inValue.idSubTipo = idSubTipo;
            WSFAlimentos.SWProducto.CreateProducto2Response retVal = ((WSFAlimentos.SWProducto.WSProducto)(this)).CreateProducto2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWProducto.CreateProducto2Response> WSFAlimentos.SWProducto.WSProducto.CreateProducto2Async(WSFAlimentos.SWProducto.CreateProducto2Request request) {
            return base.Channel.CreateProducto2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWProducto.CreateProducto2Response> CreateProducto2Async(string nombre, int precio, System.DateTime anioF, System.DateTime anioV, string descripcion, int stock, double tarifa, int idSubTipo) {
            WSFAlimentos.SWProducto.CreateProducto2Request inValue = new WSFAlimentos.SWProducto.CreateProducto2Request();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.anioF = anioF;
            inValue.anioV = anioV;
            inValue.descripcion = descripcion;
            inValue.stock = stock;
            inValue.tarifa = tarifa;
            inValue.idSubTipo = idSubTipo;
            return ((WSFAlimentos.SWProducto.WSProducto)(this)).CreateProducto2Async(inValue);
        }
    }
}
