//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAlimentos.SWBoletas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="SWBoletas.WSBoleta")]
    public interface WSBoleta {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/createBoletaRequest", ReplyAction="http://service/WSBoleta/createBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.createBoletaResponse createBoleta(WSFAlimentos.SWBoletas.createBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/createBoletaRequest", ReplyAction="http://service/WSBoleta/createBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.createBoletaResponse> createBoletaAsync(WSFAlimentos.SWBoletas.createBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/editBoletaRequest", ReplyAction="http://service/WSBoleta/editBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.editBoletaResponse editBoleta(WSFAlimentos.SWBoletas.editBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/editBoletaRequest", ReplyAction="http://service/WSBoleta/editBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.editBoletaResponse> editBoletaAsync(WSFAlimentos.SWBoletas.editBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/removeBoletaRequest", ReplyAction="http://service/WSBoleta/removeBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.removeBoletaResponse removeBoleta(WSFAlimentos.SWBoletas.removeBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/removeBoletaRequest", ReplyAction="http://service/WSBoleta/removeBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.removeBoletaResponse> removeBoletaAsync(WSFAlimentos.SWBoletas.removeBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findBoletaRequest", ReplyAction="http://service/WSBoleta/findBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.findBoletaResponse findBoleta(WSFAlimentos.SWBoletas.findBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findBoletaRequest", ReplyAction="http://service/WSBoleta/findBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findBoletaResponse> findBoletaAsync(WSFAlimentos.SWBoletas.findBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findAllBoletaRequest", ReplyAction="http://service/WSBoleta/findAllBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.findAllBoletaResponse findAllBoleta(WSFAlimentos.SWBoletas.findAllBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findAllBoletaRequest", ReplyAction="http://service/WSBoleta/findAllBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findAllBoletaResponse> findAllBoletaAsync(WSFAlimentos.SWBoletas.findAllBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findRangeBoletaRequest", ReplyAction="http://service/WSBoleta/findRangeBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.findRangeBoletaResponse findRangeBoleta(WSFAlimentos.SWBoletas.findRangeBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/findRangeBoletaRequest", ReplyAction="http://service/WSBoleta/findRangeBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findRangeBoletaResponse> findRangeBoletaAsync(WSFAlimentos.SWBoletas.findRangeBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/countBoletaRequest", ReplyAction="http://service/WSBoleta/countBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.countBoletaResponse countBoleta(WSFAlimentos.SWBoletas.countBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/countBoletaRequest", ReplyAction="http://service/WSBoleta/countBoletaResponse")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.countBoletaResponse> countBoletaAsync(WSFAlimentos.SWBoletas.countBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/CreateBoleta2Request", ReplyAction="http://service/WSBoleta/CreateBoleta2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSFAlimentos.SWBoletas.CreateBoleta2Response CreateBoleta2(WSFAlimentos.SWBoletas.CreateBoleta2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSBoleta/CreateBoleta2Request", ReplyAction="http://service/WSBoleta/CreateBoleta2Response")]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.CreateBoleta2Response> CreateBoleta2Async(WSFAlimentos.SWBoletas.CreateBoleta2Request request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class boleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idBoletaField;
        
        private bool idBoletaFieldSpecified;
        
        private ventas ventasIdventasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idBoleta {
            get {
                return this.idBoletaField;
            }
            set {
                this.idBoletaField = value;
                this.RaisePropertyChanged("idBoleta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idBoletaSpecified {
            get {
                return this.idBoletaFieldSpecified;
            }
            set {
                this.idBoletaFieldSpecified = value;
                this.RaisePropertyChanged("idBoletaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ventas ventasIdventas {
            get {
                return this.ventasIdventasField;
            }
            set {
                this.ventasIdventasField = value;
                this.RaisePropertyChanged("ventasIdventas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class ventas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoVField;
        
        private cliente clienteIdClienteField;
        
        private System.DateTime fechaEntregaField;
        
        private bool fechaEntregaFieldSpecified;
        
        private System.DateTime fechaVentaField;
        
        private bool fechaVentaFieldSpecified;
        
        private int idventasField;
        
        private bool idventasFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoV {
            get {
                return this.activoVField;
            }
            set {
                this.activoVField = value;
                this.RaisePropertyChanged("activoV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente clienteIdCliente {
            get {
                return this.clienteIdClienteField;
            }
            set {
                this.clienteIdClienteField = value;
                this.RaisePropertyChanged("clienteIdCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEntregaSpecified {
            get {
                return this.fechaEntregaFieldSpecified;
            }
            set {
                this.fechaEntregaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEntregaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVenta {
            get {
                return this.fechaVentaField;
            }
            set {
                this.fechaVentaField = value;
                this.RaisePropertyChanged("fechaVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVentaSpecified {
            get {
                return this.fechaVentaFieldSpecified;
            }
            set {
                this.fechaVentaFieldSpecified = value;
                this.RaisePropertyChanged("fechaVentaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idventas {
            get {
                return this.idventasField;
            }
            set {
                this.idventasField = value;
                this.RaisePropertyChanged("idventas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idventasSpecified {
            get {
                return this.idventasFieldSpecified;
            }
            set {
                this.idventasFieldSpecified = value;
                this.RaisePropertyChanged("idventasSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoCField;
        
        private string apellidoClienteField;
        
        private string dvField;
        
        private int edadClienteField;
        
        private estadoCivil estadoCivilIdEstadoCivilField;
        
        private short idClienteField;
        
        private bool idClienteFieldSpecified;
        
        private string nombreClienteField;
        
        private int rutField;
        
        private bool sexoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activoC {
            get {
                return this.activoCField;
            }
            set {
                this.activoCField = value;
                this.RaisePropertyChanged("activoC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoCliente {
            get {
                return this.apellidoClienteField;
            }
            set {
                this.apellidoClienteField = value;
                this.RaisePropertyChanged("apellidoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edadCliente {
            get {
                return this.edadClienteField;
            }
            set {
                this.edadClienteField = value;
                this.RaisePropertyChanged("edadCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public estadoCivil estadoCivilIdEstadoCivil {
            get {
                return this.estadoCivilIdEstadoCivilField;
            }
            set {
                this.estadoCivilIdEstadoCivilField = value;
                this.RaisePropertyChanged("estadoCivilIdEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class estadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEstadoCivilField;
        
        private short idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEstadoCivil {
            get {
                return this.descripcionEstadoCivilField;
            }
            set {
                this.descripcionEstadoCivilField = value;
                this.RaisePropertyChanged("descripcionEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta entity;
        
        public createBoletaRequest() {
        }
        
        public createBoletaRequest(WSFAlimentos.SWBoletas.boleta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createBoletaResponse() {
        }
        
        public createBoletaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta entity;
        
        public editBoletaRequest() {
        }
        
        public editBoletaRequest(WSFAlimentos.SWBoletas.boleta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editBoletaResponse() {
        }
        
        public editBoletaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta entity;
        
        public removeBoletaRequest() {
        }
        
        public removeBoletaRequest(WSFAlimentos.SWBoletas.boleta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeBoletaResponse() {
        }
        
        public removeBoletaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findBoletaRequest() {
        }
        
        public findBoletaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta @return;
        
        public findBoletaResponse() {
        }
        
        public findBoletaResponse(WSFAlimentos.SWBoletas.boleta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllBoletaRequest {
        
        public findAllBoletaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta[] @return;
        
        public findAllBoletaResponse() {
        }
        
        public findAllBoletaResponse(WSFAlimentos.SWBoletas.boleta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeBoletaRequest() {
        }
        
        public findRangeBoletaRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSFAlimentos.SWBoletas.boleta[] @return;
        
        public findRangeBoletaResponse() {
        }
        
        public findRangeBoletaResponse(WSFAlimentos.SWBoletas.boleta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countBoleta", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countBoletaRequest {
        
        public countBoletaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countBoletaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countBoletaResponse() {
        }
        
        public countBoletaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBoleta2", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateBoleta2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idVenta;
        
        public CreateBoleta2Request() {
        }
        
        public CreateBoleta2Request(int idVenta) {
            this.idVenta = idVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBoleta2Response", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateBoleta2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CreateBoleta2Response() {
        }
        
        public CreateBoleta2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBoletaChannel : WSFAlimentos.SWBoletas.WSBoleta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBoletaClient : System.ServiceModel.ClientBase<WSFAlimentos.SWBoletas.WSBoleta>, WSFAlimentos.SWBoletas.WSBoleta {
        
        public WSBoletaClient() {
        }
        
        public WSBoletaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBoletaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBoletaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBoletaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.createBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.createBoleta(WSFAlimentos.SWBoletas.createBoletaRequest request) {
            return base.Channel.createBoleta(request);
        }
        
        public bool createBoleta(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.createBoletaRequest inValue = new WSFAlimentos.SWBoletas.createBoletaRequest();
            inValue.entity = entity;
            WSFAlimentos.SWBoletas.createBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).createBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.createBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.createBoletaAsync(WSFAlimentos.SWBoletas.createBoletaRequest request) {
            return base.Channel.createBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.createBoletaResponse> createBoletaAsync(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.createBoletaRequest inValue = new WSFAlimentos.SWBoletas.createBoletaRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).createBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.editBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.editBoleta(WSFAlimentos.SWBoletas.editBoletaRequest request) {
            return base.Channel.editBoleta(request);
        }
        
        public bool editBoleta(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.editBoletaRequest inValue = new WSFAlimentos.SWBoletas.editBoletaRequest();
            inValue.entity = entity;
            WSFAlimentos.SWBoletas.editBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).editBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.editBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.editBoletaAsync(WSFAlimentos.SWBoletas.editBoletaRequest request) {
            return base.Channel.editBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.editBoletaResponse> editBoletaAsync(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.editBoletaRequest inValue = new WSFAlimentos.SWBoletas.editBoletaRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).editBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.removeBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.removeBoleta(WSFAlimentos.SWBoletas.removeBoletaRequest request) {
            return base.Channel.removeBoleta(request);
        }
        
        public bool removeBoleta(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.removeBoletaRequest inValue = new WSFAlimentos.SWBoletas.removeBoletaRequest();
            inValue.entity = entity;
            WSFAlimentos.SWBoletas.removeBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).removeBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.removeBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.removeBoletaAsync(WSFAlimentos.SWBoletas.removeBoletaRequest request) {
            return base.Channel.removeBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.removeBoletaResponse> removeBoletaAsync(WSFAlimentos.SWBoletas.boleta entity) {
            WSFAlimentos.SWBoletas.removeBoletaRequest inValue = new WSFAlimentos.SWBoletas.removeBoletaRequest();
            inValue.entity = entity;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).removeBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.findBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.findBoleta(WSFAlimentos.SWBoletas.findBoletaRequest request) {
            return base.Channel.findBoleta(request);
        }
        
        public WSFAlimentos.SWBoletas.boleta findBoleta(int id) {
            WSFAlimentos.SWBoletas.findBoletaRequest inValue = new WSFAlimentos.SWBoletas.findBoletaRequest();
            inValue.id = id;
            WSFAlimentos.SWBoletas.findBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.findBoletaAsync(WSFAlimentos.SWBoletas.findBoletaRequest request) {
            return base.Channel.findBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findBoletaResponse> findBoletaAsync(int id) {
            WSFAlimentos.SWBoletas.findBoletaRequest inValue = new WSFAlimentos.SWBoletas.findBoletaRequest();
            inValue.id = id;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.findAllBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.findAllBoleta(WSFAlimentos.SWBoletas.findAllBoletaRequest request) {
            return base.Channel.findAllBoleta(request);
        }
        
        public WSFAlimentos.SWBoletas.boleta[] findAllBoleta() {
            WSFAlimentos.SWBoletas.findAllBoletaRequest inValue = new WSFAlimentos.SWBoletas.findAllBoletaRequest();
            WSFAlimentos.SWBoletas.findAllBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findAllBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findAllBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.findAllBoletaAsync(WSFAlimentos.SWBoletas.findAllBoletaRequest request) {
            return base.Channel.findAllBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findAllBoletaResponse> findAllBoletaAsync() {
            WSFAlimentos.SWBoletas.findAllBoletaRequest inValue = new WSFAlimentos.SWBoletas.findAllBoletaRequest();
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findAllBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.findRangeBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.findRangeBoleta(WSFAlimentos.SWBoletas.findRangeBoletaRequest request) {
            return base.Channel.findRangeBoleta(request);
        }
        
        public WSFAlimentos.SWBoletas.boleta[] findRangeBoleta(System.Nullable<int>[] range) {
            WSFAlimentos.SWBoletas.findRangeBoletaRequest inValue = new WSFAlimentos.SWBoletas.findRangeBoletaRequest();
            inValue.range = range;
            WSFAlimentos.SWBoletas.findRangeBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findRangeBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findRangeBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.findRangeBoletaAsync(WSFAlimentos.SWBoletas.findRangeBoletaRequest request) {
            return base.Channel.findRangeBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.findRangeBoletaResponse> findRangeBoletaAsync(System.Nullable<int>[] range) {
            WSFAlimentos.SWBoletas.findRangeBoletaRequest inValue = new WSFAlimentos.SWBoletas.findRangeBoletaRequest();
            inValue.range = range;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).findRangeBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.countBoletaResponse WSFAlimentos.SWBoletas.WSBoleta.countBoleta(WSFAlimentos.SWBoletas.countBoletaRequest request) {
            return base.Channel.countBoleta(request);
        }
        
        public int countBoleta() {
            WSFAlimentos.SWBoletas.countBoletaRequest inValue = new WSFAlimentos.SWBoletas.countBoletaRequest();
            WSFAlimentos.SWBoletas.countBoletaResponse retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).countBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.countBoletaResponse> WSFAlimentos.SWBoletas.WSBoleta.countBoletaAsync(WSFAlimentos.SWBoletas.countBoletaRequest request) {
            return base.Channel.countBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.countBoletaResponse> countBoletaAsync() {
            WSFAlimentos.SWBoletas.countBoletaRequest inValue = new WSFAlimentos.SWBoletas.countBoletaRequest();
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).countBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAlimentos.SWBoletas.CreateBoleta2Response WSFAlimentos.SWBoletas.WSBoleta.CreateBoleta2(WSFAlimentos.SWBoletas.CreateBoleta2Request request) {
            return base.Channel.CreateBoleta2(request);
        }
        
        public string CreateBoleta2(int idVenta) {
            WSFAlimentos.SWBoletas.CreateBoleta2Request inValue = new WSFAlimentos.SWBoletas.CreateBoleta2Request();
            inValue.idVenta = idVenta;
            WSFAlimentos.SWBoletas.CreateBoleta2Response retVal = ((WSFAlimentos.SWBoletas.WSBoleta)(this)).CreateBoleta2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.CreateBoleta2Response> WSFAlimentos.SWBoletas.WSBoleta.CreateBoleta2Async(WSFAlimentos.SWBoletas.CreateBoleta2Request request) {
            return base.Channel.CreateBoleta2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSFAlimentos.SWBoletas.CreateBoleta2Response> CreateBoleta2Async(int idVenta) {
            WSFAlimentos.SWBoletas.CreateBoleta2Request inValue = new WSFAlimentos.SWBoletas.CreateBoleta2Request();
            inValue.idVenta = idVenta;
            return ((WSFAlimentos.SWBoletas.WSBoleta)(this)).CreateBoleta2Async(inValue);
        }
    }
}
